name: Actualizar archivo en otro repositorio

on:
  push:
    branches:
      - master
    paths:
      - readme.md
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - readme.md

jobs:
  actualizar-archivo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Actualizar archivo
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "Nombre de usuario"
        git config --global user.email "correo@example.com"
        git clone git@github.com:MendiburuFrancisco/mendiburufrancisco.github.io.git
        mv readme.md mendiburufrancisco.github.io/assets/md/
        cd mendiburufrancisco.github.io/assets/md/
        rm ferreteria.md
        mv readme.md ferreteria.md
        git add .
        git commit -m "Actualización automática del archivo"
        git push origin main
    # - name: Actualizar archivo
    #   run: |
    #     # git config --global user.name "MendiburuFrancisco"
    #     # git config --global user.email "franmendi.fm@gmail.com"
    #     # git clone    https://github.com/MendiburuFrancisco/mendiburufrancisco.github.io.git
    #     git clone    git@github.com:MendiburuFrancisco/mendiburufrancisco.github.io.git
    #     mv ./readme.md mendiburufrancisco.github.io/assets/md/
    #     cd mendiburufrancisco.github.io/assets/md/
    #     rm ferreteria.md
    #     mv readme.md ferreteria.md
    #     git add .
    #     git commit -m "Actualización automática del archivo"
    #     git push